### ISSUE TITLE
td(base): unify NullifierLeafPreimage types across circuits and barretenberg

### ISSUE THREAD

**Issue by Maddiaa0** [AztecProtocol/aztec3-circuits#147]
# Overview
Currently circuits uses a distinct nullifier pre-image type to barretenberg, this introduces verbose code with unnecessary casting. 

AC1: 
- `NullifierLeafPreimage<NCT>` should be compatible with barretenberg's `nullifier_leaf` type

**Comment by Maddiaa0** [comment]
@iAmMichaelConnor 
Looking into this ticket, it seems like I will need to implement the nullifier_leaf within barretenberg to be NCT typed. Do we want the NCT abstraction inside barretenberg?

**Comment by iAmMichaelConnor** [comment]
Hi - sorry I missed this.
No, we don't want any `NCT` inside bberg.
In what ways are they incompatible? And could we use the bberg version directly? Might be worth a call :)

**Comment by dbanks12** [comment]
@Maddiaa0 is this still an issue?

**Comment by Maddiaa0** [comment]
Not an immediate issue tbh, may be when we come to write the circuits and there is no circuit type for this object, but that can be quickly fixed

**Comment by iAmMichaelConnor** [comment]
Closing as moved to 'Done' (it's a github bug)
