### ISSUE TITLE
Nullifier logic - Merge Rollup Circuit

### ISSUE THREAD

**Issue by LHerskind** [AztecProtocol/aztec3-circuits#159]
After the design changes to move more computation into the base. The merge is not actively inserting any new nullifiers into the trees. Instead it should ensure that the end snapshot of the left child matches the start of the right, e.g., ensuring that the right tree builds on the left.

Merge were not included in the hackathon code. So need some changes to support it in between base and root.

Related to #160

**Comment by rahul-kothari** [comment]
Completed in https://github.com/AztecProtocol/aztec3-circuits/pull/153
