### ISSUE TITLE
Change empty leaf of the nullifier tree

### ISSUE THREAD

**Issue by LHerskind** [AztecProtocol/aztec3-circuits#161]
Implement the successor merkle tree for nullifiers in the base with batch insertion. There are double-spend issues if using batch insertion as in normal merkle tree which need to be addressed in this separately. 

The double-spend case is when the same predecessor is to be updated multiple times, such that one of the pending should have a predecessor in the pending set and not outside. Also need to address the 0 leaf insertions and not use empty leafs as base as it is possible to point an empty leaf to anything creating a "split" in the tree.

**Comment by iAmMichaelConnor** [comment]
Closing because moved to 'Done'
