### ISSUE TITLE
Standardize usage of namespaces & includes

### ISSUE THREAD

**Issue by iAmMichaelConnor** [AztecProtocol/aztec3-circuits#190]
E.g. there are several confusing namespaces being used in the base rollup files. Perhaps we could get away with a single namespace (Edit: for base rollup)?
Ideally, the namespace structure (and naming) should match the directory structure (and naming).

**Comment by dbanks12** [comment]
As part of this PR, remove all cases of using-entire-namespace (`using namespace <MYNAMESPACE>;`) which leads to pollution.

When this PR is done, the following `WarningsAsErrors` omissions should be removed from `.clang-tidy` which will promote this deviation from our standard to an error: `-google-build-using-namespace,` ([config here](https://github.com/AztecProtocol/aztec3-packages/pull/415/files#diff-c402e508049a081befe82d6b4f4691f8c78bc56b617e5960787811e7cfa242c8R70) and remove/update comments [here](https://github.com/AztecProtocol/aztec3-packages/pull/415/files#diff-c402e508049a081befe82d6b4f4691f8c78bc56b617e5960787811e7cfa242c8R50) and [here](https://github.com/AztecProtocol/aztec3-packages/pull/415/files#diff-c402e508049a081befe82d6b4f4691f8c78bc56b617e5960787811e7cfa242c8R131)).
