### ISSUE TITLE
Improve Github Project automation

### ISSUE THREAD

**Issue by iAmMichaelConnor** [AztecProtocol/aztec3-circuits#192]
There are a few actions which _should_ be closing our issues automatically, but that's not happening...

- Move a kanban tile into 'Done' in the Project A3 (https://github.com/orgs/AztecProtocol/projects/22)
- Merge a PR which references the issue with 'closes' or 'fixes' or 'resolves'.

Might anyone know why that's not working?

**Comment by spalladino** [comment]
> Move a kanban tile into 'Done' in the Project A3 (https://github.com/orgs/AztecProtocol/projects/22)

I believe github automation works the other way around: it moves the tile into Done when you mark the issue as completed.

> Merge a PR which references the issue with 'closes' or 'fixes' or 'resolves'.

That's working for me (see https://github.com/AztecProtocol/aztec3-packages/pull/238 as an example)

**Comment by dbanks12** [comment]
@iAmMichaelConnor is this ticket still relevant?
