### ISSUE TITLE
Add a secret into the contract leaf

### ISSUE THREAD

**Issue by iAmMichaelConnor** [AztecProtocol/aztec3-circuits#195]
We should insert a secret into the contract leaf to ensure that an attacker cannot try all widely used function_tree_roots and figure out what your code is. example, you want to have a private multisig, but it uses a battletested implementation, without the secret, it is possible to figure out that it is a mulitisig.

**Comment by dbanks12** [comment]
If you dont add randomness to function leaf, you might be able to brute force a common algo (erc20, multisig).

**Comment by dbanks12** [comment]
Closing, replaced in aztec-packages by https://github.com/AztecProtocol/aztec-packages/issues/1043
