### ISSUE TITLE
Rename storage_contract_address to contract_address

### ISSUE THREAD

**Issue by iAmMichaelConnor** [AztecProtocol/aztec3-circuits#196]

**Comment by iAmMichaelConnor** [comment]
@dbanks12 I think it should stay as `storage_contract_address` for this particular data member of the call_context.
The reason being, for delegatecalls (when we introduce them), contract B might be 'delegatecalled' by contract A, but when executing the function in contract B, it will retain the _storage_ contract address of contract A (i.e. the storage slots of contract A will be edited).

I'll leave the issue open for a little while for discussion, though :)

**Comment by dbanks12** [comment]
> @dbanks12 I think it should stay as `storage_contract_address` for this particular data member of the call_context. The reason being, for delegatecalls (when we introduce them), contract B might be 'delegatecalled' by contract A, but when executing the function in contract B, it will retain the _storage_ contract address of contract A (i.e. the storage slots of contract A will be edited).
> 
> I'll leave the issue open for a little while for discussion, though :)

Ahh I see. Thanks for the explanation. Makes sense to me 👍
