### ISSUE TITLE
Add CONTRIBUTING info

### ISSUE THREAD

**Issue by iAmMichaelConnor** [AztecProtocol/aztec3-circuits#199]
Add a CONTRIBUTING.md file for newcomers to understand how best they can help out!

**Comment by harisdev-netizen** [comment]
Hello there @iAmMichaelConnor can I work on this?

**Comment by dbanks12** [comment]
Sure @harisdev-netizen! We are now working out of https://github.com/AztecProtocol/aztec-packages. There is a top-level readme and there is also a `README.md` and `CODING_STANDARD.md` under `circuits/`, but they may be lacking quite a bit!

Replacing with issue in aztec-packages repo: https://github.com/AztecProtocol/aztec3-circuits/issues/199
