### ISSUE TITLE
Spike: reconsider `function_selector` bit-length 

### ISSUE THREAD

**Issue by iAmMichaelConnor** [AztecProtocol/aztec3-circuits#204]
Consider whether the `function_selector` should be a uint32 (4 bytes) instead of a field, inside our c++ structs.

We can always cast it to a field when including it in hashes.

There's been some criticism of 4-byte function selectors in ethereum [citation needed], so an alternative is to use an entire field (but even that isn't straightforward, because a keccak output is 256-bits, not 254).

**Comment by benesjan** [comment]
[Relevant discussion](https://aztecprotocol.slack.com/archives/C03P17YHVK8/p1681900937960679) on slack.

TLDR:
Wait for local devnet to be finished and then reconsider. Before mainnet it's easy to change.

**Comment by dbanks12** [comment]
Replaced by https://github.com/AztecProtocol/aztec-packages/issues/1050
