### ISSUE TITLE
Remove 'mock circuit' proof generation

### ISSUE THREAD

**Issue by iAmMichaelConnor** [AztecProtocol/aztec3-circuits#209]
In order to generate a dummy private kernel VK and proof, we currently generate a proving key, verification key, and a proof over a 'mock circuit'.
This slows down the whole Local Developer Testnet significantly (notably, the e2e tests in aztec3-packages, possibly by tens of seconds).
Eventually this will go away with https://github.com/AztecProtocol/aztec3-circuits/issues/200 (separating the 'initial' case from the 'recursive' case). But as a stop-gap, let's try to hard-code a stub VK and Proof, and use those. I.e. a PR for this issue should only have mock circuits being used in c++ tests.

**Comment by dbanks12** [comment]
Native tests are now using a hardcoded VK and Proof, but circuit tests still use the mock circuit proof gen. Is this sufficient @iAmMichaelConnor?

**Comment by dbanks12** [comment]
Last step here for now is to change the `dummy_previous_kernel` cbind to accept an optional argument "real_vk_proof" (or something similar) and forward that to the inner helper function. Default will be `false` and will return a previous kernel with a truly dumb vk and proof. If `true` it will use the mock kernel to generate a real vk and proof. TS will need to be updated with this change.
