### ISSUE TITLE
ECDSA Public Key Recovery in Native C++

### ISSUE THREAD

**Issue by suyash67** [AztecProtocol/aztec3-circuits#210]
We need to pass in the secp256k1 public key as input to the private kernel circuit (as a part of `TxContext`). However, we don't want TS to be able to figure out the public key from a given Ethereum address. Instead, we would like native C++ to recover the public from the signature and then check in the circuit if it corresponds to the provided ethereum address.

**Comment by iAmMichaelConnor** [comment]
Closing because moved to 'Done'
