### ISSUE TITLE
Spike: where to put the L1->L2 message inserting logic? Root or Merge?

### ISSUE THREAD

**Issue by iAmMichaelConnor** [AztecProtocol/aztec3-circuits#230]
I think let's put this insertion logic into the root rollup circuit.
A merge rollup circuit should only deal with verifying information about new txs; specifically the new txs which it is 'merging'. New L1->L2 messages don't fall in that category: they're information which was produced in a previous rollup. Eventually we'll probably write a separate circuit to push these new messages into the append-only tree. But for now, let's add logic to the root rollup circuit.

What do you think @LHerskind?

**Comment by iAmMichaelConnor** [comment]
> It is not information from a previous rollup when going L1 -> L2, the information can come independently of the rollups

Ah, yeah, my bad. 

> main reasoning behind not doing that would just be that we are then moving the burden onto just one of the proofs

Yeah, exactly. I suppose another reason for not doing it in the root rollup, is it hard-codes an upper bound on how many new l1->l2 messages can be inserted with each l2 block.

If you fancy it, you could write a separate circuit (called something like `message_insertion` circuit), whose proof then gets verified within the root rollup circuit? And (longer term) we could compile many different 'sizes' of `message_insertion` circuit, and the root rollup could permit any of their verification keys to be used when being verified within it.

**Comment by LHerskind** [comment]
> Yeah, exactly. I suppose another reason for not doing it in the root rollup, is it hard-codes an upper bound on how many new l1->l2 messages can be inserted with each l2 block.

There will indirectly be a bound of this anyway, as it is updating storage on L1, there is an inherit limit that is much more "heavy" than just the data cost.

**Comment by iAmMichaelConnor** [comment]
Closing because moved to 'Done'
