### ISSUE TITLE
compilation: Investigate USE_TURBO flag at the circuits level  

### ISSUE THREAD

**Issue by cheethas** [AztecProtocol/aztec3-circuits#236]
# Description

When making calls to `hash_pair_native` from barretenberg,  one version of the pedersen hash function is used, but when calls are made from libraries built in a3circuits they use another version. 

![image](https://user-images.githubusercontent.com/47148561/231578093-29c2a303-9ca1-4dd5-9daf-b862dee72503.png)
This is due to the plonk::SYSTEM_COMPOSER flag being different in each build environment.

The following lines have been added to `aztec3-circuits/cpp/CMakeLists.txt`
```
option(USE_TURBO "Enable the use of TurboPlonk in barretenberg." OFF)
if(USE_TURBO)
    message(STATUS "Building barretenberg for TurboPlonk Composer.")
    add_definitions(-DUSE_TURBO)
else()
    message(STATUS "Building barretenberg for UltraPlonk Composer.")
endif()
```
this fixes the issue when building with the following instructions:
```
cmake --preset clang15 -DUSE_TURBO=true
cmake --build --preset clang15
```

## Reproduction
1. checkout the following commit: `14b05304d70b3faaf06f76418ea286204ee6ecd9`
1. `cmake --build --preset default`
1. `(cd build && ./bin/aztec3_circuits_rollup_tests )` - will result in failing tests due to differing hashes being used at different points

**Comment by dbanks12** [comment]
During debugging we discovered that if we build bberg with `USE_TURBO=true` but not `aztec3-circuits`, then SOME of the bberg functions/files we `#include` in our circuits would use PLOOKUP and others would use TURBO.

Does this mean that in some instances we are using compiled object files from the barretenberg library archive, but in other instances we are just using bberg headers directly from our circuits?

How do we avoid this in the future with out preprocessor definitions? @phated @ludamad @adr1anh

**Comment by phated** [comment]
😬 I made the `USE_TURBO` change but that was only guided by failing cmake builds. I think https://github.com/AztecProtocol/barretenberg/pull/352 is supposed to supersede my hack to try to keep turbo around for a3

**Comment by dbanks12** [comment]
Closing this since the `USE_TURBO` flag was removed in bberg master. We still need to make some decisions on how to easily toggle between different composers and pedersen implementations. But this ticket itself can be closed.
