### ISSUE TITLE
Refactor C-bindings to adhere to new ABI format and rules

### ISSUE THREAD

**Issue by ludamad** [AztecProtocol/aztec3-circuits#244]
We need to convert our existing C-bindings from the current loose format to a new, more strict format. The new format is defined by the following rules:

CBind constraints:
- All functions should return void, or, preferably, either a serialized error object (which will be freed by the TypeScript or Rust caller), or, in the common case, a nullptr.
- All functions can have an arbitrary number of input and output args.
- All arguments must be pointers except raw 32-bit integers
- Prefer to input and output encoded variable length objects than passing size pointers. These have their size as the first 4 bytes, and then the rest of the elements.
- If you pass size pointers, they go before the object
- Input args are determined by being const or pointer to const, and end with "_in"
- Output args must come after input args, and end with "_out"
- The TypeScript or Rust binding function is responsible for allocating argument memory (including output memory).
- The TypeScript or Rust binding function will free any variable length output args that were allocated on the heap.
- Variable length output args are allocated on the heap, and the resulting pointer is written to the output arg ptr

Serialization constraints (for completeness, should already be true):
- All input data is big-endian.
- All output data is big-endian, except output heap alloc pointers.

The idea then is we would route all the bindings through a standard helper function, which even if we don't go full autogeneration (like we plan to consider), it will take a lot of mystery out of writing bindings:

https://github.com/AztecProtocol/barretenberg/blob/cl/ts/ts/src/call_wasm_export/index.ts

Example new bindings:

https://github.com/AztecProtocol/barretenberg/blob/cl/ts/ts/src/bindings/index.ts

Example CBind refactor:

```
WASM_EXPORT size_t root_rollup__sim(uint8_t const* root_rollup_inputs_buf,
                                    uint8_t const** root_rollup_public_inputs_buf)
```
to

```
WASM_EXPORT void root_rollup__sim(uint8_t const* root_rollup_inputs_in,
                                  size_t* root_rollup_public_inputs_size_out, uint8_t** root_rollup_public_inputs_out)
```

**Task**
- Identify all the C-bindings in the codebase that need to be refactored according to the new format and rules.
- Modify the functions to follow the new ABI format, ensuring input and output arguments adhere to the rules.
- Update the binding formats to route through a uniform wrapper that understands the current format.
- Test the refactored functions to ensure proper functionality and compatibility with the new format.

**Comment by spalladino** [comment]
Thanks for putting this together, it was much needed (see https://github.com/AztecProtocol/aztec3-packages/issues/210). Agree on the new rules, I'd just add another one to define the ordering between a buf and its size. In other words, using your example, only one of these should be correct:

```c++
WASM_EXPORT void root_rollup__sim(
  uint8_t const* root_rollup_inputs_in,
  uint8_t** root_rollup_public_inputs_out, 
  size_t* root_rollup_public_inputs_size_out
)
```

```c++
WASM_EXPORT void root_rollup__sim(
  uint8_t const* root_rollup_inputs_in,
  size_t* root_rollup_public_inputs_size_out
  uint8_t** root_rollup_public_inputs_out, 
)
```

Also, should we integrate into the guidelines the work that @rahul-kothari is doing about returning error information? Maybe it makes sense to have all functions return an `ok/error(err)` object instead of void?

**Comment by ludamad** [comment]
Good call. I guess it could return nullptr (fast case) or a serialized error object.

**Comment by ludamad** [comment]
We could possibly also just use length-encoded buffers everywhere. The size would be the first 4 bytes

**Comment by spalladino** [comment]
> We could possibly also just use length-encoded buffers everywhere

I believe that'd help catch its own fair share of errors already. You can easily check if lengths match rather than trusting that the caller built a buffer with the same size you think it did.

**Comment by dbanks12** [comment]
I agree with all of this, and yes we should probably standardize to return an error code and message as @rahul-kothari has proposed.

**Comment by dbanks12** [comment]
GPT4 summary of a recent internal slack thread.

**Title: Error Handling Standardization for Cbinds**
Issue:
In a recent discussion, the team debated the pros and cons of using error objects versus error codes for error handling in cbinds. The primary concern was to ensure that error messages can be easily communicated across the stack or to users.
Error objects offer the ability to include more detailed information, such as the value of an invalid argument. However, error codes are simpler to integrate and might be more suitable for scenarios where TypeScript (TS) might not need the error message.
There was also a discussion on whether this error handling standardization should be implemented just for circuits or for all cbinds in Barretenberg. The consensus was to start small with circuits and expand later if necessary.
Proposed Solution:
The team agreed that using error objects with both a code and dynamic message would be the cleanest approach.


Additionally, the team agreed to print error messages before returning from the cbind, ensuring that errors are evident even if there are issues with processing the error object in TS.
Finally, it was decided to give the Barretenberg team an FYI on the error handling standardization and proceed with the implementation for circuits.

**Comment by dbanks12** [comment]
Just paired with @rahul-kothari on this. The current plan is to create an Error object in C++, allocate a `uint8_t*` buffer, serialize to that buffer and return it to TS. The Error object (code and dynamic-length message).

Will TS need to know the full size of the returned buffer? The only dynamic-length member of Error is its message (string). When Error is serialized, `write()` first writes the string's length before writing its chars. But I suspect that TS will need to know the exact length of the buffer it even attempts to deserialize?

**Comment by dbanks12** [comment]
Also does anyone have opinions on error object names?

**Comment by spalladino** [comment]
That sounds good to me. I don't think TS will need to know the full error length if the string length is already encoded in there. Two questions:

1- Does it make sense to return the error code directly from the function? So the function would return two uint8s: one for the code, and one for the pointer to the error message string. This way we can get the error message directly in the return value, rather than having to another part of memory to retrieve it.

2- Who's responsible for freeing the memory allocated for the string error message? Is it ts? Or are we keeping a memory scratch area, that doesn't require freeing, for keeping the latest error msg string?

**Comment by rahul-kothari** [comment]
1. No strong opinion although for now I just return a ptr.
2. Looking at our TS - `rollupWasmWrapper`, we have:
```
     // Free memory
      wasm.call('bbfree', outputBufPtr);
      wasm.call('bbfree', outputBufPtrPtr);
      wasm.call('bbfree', inputBufPtr);
```
So I guess continue freeing memory from TS?

**Comment by dbanks12** [comment]
> That sounds good to me. I don't think TS will need to know the full error length if the string length is already encoded in there. Two questions:
> 
> 1- Does it make sense to return the error code directly from the function? So the function would return two uint8s: one for the code, and one for the pointer to the error message string. This way we can get the error message directly in the return value, rather than having to another part of memory to retrieve it.
> 
> 2- Who's responsible for freeing the memory allocated for the string error message? Is it ts? Or are we keeping a memory scratch area, that doesn't require freeing, for keeping the latest error msg string?

1. Hmm I do like the idea of having the error code immediately accessible without any memory handling. Do you forsee that being valuable @spalladino? It does feel pretty clean.
2. It would be TS' responsibility to free the serialized error object which includes the serialized msg string.

**Comment by spalladino** [comment]
> Hmm I do like the idea of having the error code immediately accessible without any memory handling. Do you forsee that being valuable @spalladino? It does feel pretty clean.

It does sound good, but I don't know enough wasm to know whether it's actually valuable. @ludamad I'll defer to you on this one.

**Comment by ludamad** [comment]
I'm currently automatically-deduce-cbinds pilled and that would mean the error would just the serialization of an std::variant return type, and the args a serialization of std::tuple<Args...>. We could pick up the error result on TS side and turn it into an exception. But the relies on msgpack type safety, so not quite yet. For now I think memory handling is not really a big deal - we have to memory allocate to make the std::string error, so not seeing why it might fail called from TS right after

**Comment by rahul-kothari** [comment]
Update - once https://github.com/AztecProtocol/aztec-packages/pull/464 is merged, all error handling stuff is done

**Comment by benesjan** [comment]
No longer relevant after rewriting circuits in Noir.
