### ISSUE TITLE
Bberg issue: refactor Merkle Tree functions

### ISSUE THREAD

**Issue by iAmMichaelConnor** [AztecProtocol/aztec3-circuits#247]
It's low priority, but the functions in the Merkle Tree class could mostly be removed in favour of a few:
- Compute a root from a set of leaves
- Compute a root using a value, leaf index, and sibling path
- Get a sibling path

We've written some functions that do this inside the circuits c++ code - they should be moved as part of this refactor.

That's about it...?

**Comment by dbanks12** [comment]
Replaced by https://github.com/AztecProtocol/aztec-packages/issues/1048
