### ISSUE TITLE
CircleCI doesn't Trigger on Updating Submodule

### ISSUE THREAD

**Issue by suyash67** [AztecProtocol/aztec3-circuits#33]
Circleci doesn't run the compilation and tests if we only change the submodule (e.g. point to the latest commit in the submodule). We want circleci to be triggered even if anything doesn't change in `aztec3-circuits` but any submodule is changed.

**Comment by suyash67** [comment]
Just notices that if I push a commit that updates a submodule, circleci wrongly shows a green tick ✅ when it should compile everything from scratch. (It just refers to some old green tick and avoids running any tests)

**Comment by iAmMichaelConnor** [comment]
@suyash67 is this still an issue?

**Comment by dbanks12** [comment]
Closing this as I believe I know what was causing this a while back (issue with the way our CI scripts were looking for submodule bumps) and it has been fixed.
