### ISSUE TITLE
Implement a native stdlib in bberg

### ISSUE THREAD

**Issue by iAmMichaelConnor** [AztecProtocol/aztec3-circuits#34]
If we implement an exact copy of all the classes and methods in the stdlib, but for native computations (i.e. the body of each function would be native), we can unify every struct/class/method/function to be templated over 'NativeOrCircuitTypes' (`NCT`).

It would use a `NativeComposer`, which has the same interface as the `BaseComposer`, but of course some of those methods would be no-ops (because we don't want to build any gates when running natively!)

**Comment by iAmMichaelConnor** [comment]
#175 is a stop-gap. Eventually we should implement a native version of the entire stdlib.

**Comment by dbanks12** [comment]
Closing as this may be unnecessary if we get a fully DummyComposer working in barretenberg. Also this issue would belong in bberg anyway.
