### ISSUE TITLE
Native Base Rollup Circuit Implementation (Contract Deployment logic)

### ISSUE THREAD

**Issue by iAmMichaelConnor** [AztecProtocol/aztec3-circuits#47]
See diagram: https://miro.com/app/board/uXjVPlafJWM=/

**Comment by cheethas** [comment]
I'm onboarding to this now and am willing to have a go at it

**Comment by iAmMichaelConnor** [comment]
Thanks! Closing this, now that we've got something in place. Any tweaks can be new issues :)
